### ISSUE TITLE
Following pagination leads to surprising results

### ISSUE THREAD

**Issue by mmeierer** [TUVIMEN/xenforo#3]
Let's assume I try to run the following code
`! xenforo -N -p 4 -d '/datasets/deepnotetogoogledrive/watchuseek/sinn.24_2' -f 'https://www.watchuseek.com/forums/sinn.24/' 
`
Thus subforum has many threads (273 pages of threads).

All threads from the first page are downloaded correctly. So far, everything works great.

However, instead of going to the second page it goes to a "subforum" within this subforum. It highlighted the "subforum" that I mean, in the screeshot below. 

![image](https://user-images.githubusercontent.com/5850777/220370047-ea119a82-fc97-42a2-8e2e-26ab3d0af636.png)

I tried the various option -c / -f / -t, but none did work to follow the pagination.

This might be again because of a specific modification of this version of xenforo.

**Comment by TUVIMEN** [comment]
The script by default gets subforums ofter downloading the threads below.
Forum Rules & Guidelines is just thread presented as subforum and script treats it as such so it does not find any thread links and goes to German watches.

The problem is that the site adds california-page-nav-jump-next class to every next button, that has been [fixed](https://github.com/TUVIMEN/xenforo/commit/91fba9ffec00f458a6198279818b0c3d102f1887) by ignoring classes other than 'pageNav-jump pageNav-jump--next'.

Next buttons also corrupted downloading of the threads as the script was downloading only the first page of them. You might want to redownload them.

**Comment by mmeierer** [comment]
Awesome! Now it works. Thank you so much for your help and quick feedback. I appreciate it very much!
